import { describe, expect, it } from "vitest";
import { makeRequest, normalizeResearchResponse, selectInitialEvidence, WORKS } from "./investigativeQaClient.ts";
const base = { status: "ok", answer_text: "texto", conversation: { conversation_id: null, turn_id: null }, hits: [], evidence_matrix: [], cross_corpus_matrix: [] };
const hit = (id: string, relevance = "single_term_literal") => ({ hit_id: id, work_code: "kitzur", work_title: "Kitzur", pdf_page: null, printed_page: null, quote: "texto canónico", snippet: "…texto canónico", evidence_type: "literal_same_page", literal_strength: "strong", evidence_strength: relevance === "direct_relation" ? "strong" : "insufficient", relation_relevance: relevance, matched_terms: ["sangre"], matched_concepts: ["sangre"], is_primary: relevance === "direct_relation", source_layer: "unknown", warnings: [] });
describe("research contract", () => {
  it("normalizes optional arrays and preserves null", () => { const r = normalizeResearchResponse(base); expect(r.hits).toEqual([]); expect(r.warnings).toEqual([]); expect(r.conversation.conversation_id).toBeNull(); expect(r.answer_markdown).toBe("texto"); });
  it("rejects unknown states and missing answers", () => { expect(() => normalizeResearchResponse({ ...base, status: "broken" })).toThrow(); expect(() => normalizeResearchResponse({ ...base, answer_text: undefined })).toThrow(); });
  it("rejects malformed structured evidence", () => { expect(() => normalizeResearchResponse({ ...base, hits: [{ quote: "missing identity" }] })).toThrow(/evidencia incompatible/); expect(() => normalizeResearchResponse({ ...base, evidence_matrix: [{ work_code: "lh", hits: "2" }] })).toThrow(/matriz incompatible/); });
  it("allowlists values and truncates history", () => { const history = Array.from({ length: 20 }, (_, i) => ({ question: String(i) })); const r = makeRequest("q", { works: ["lh", "bad"], languages: ["es", "xx" as never], thematic: false, maxHits: 7 }, history, null, null); expect(r.works).toEqual(["lh"]); expect(r.languages).toEqual(["es"]); expect(r.max_hits_per_work).toBe(10); expect(r.conversation.history).toHaveLength(15); expect(r.include_audit).toBe(false); });
  it("prevents empty filters", () => { const r = makeRequest("q", { works: [], languages: [], thematic: true, maxHits: 5 }, [], null, null); expect(r.works).toEqual([...WORKS]); expect(r.languages).toEqual(["es"]); });
  it("selects explicit primary evidence instead of the first literal hit", () => { const r = normalizeResearchResponse({ ...base, hits: [hit("noise"), hit("primary", "direct_relation")], claims: [{ claim_id: "claim_1", text: "relación", strength: "strong", evidence_ids: ["primary"], primary_evidence_id: "primary" }], primary_evidence_ids: ["primary"], evidence_counts: { primary: 1, contextual: 0, additional_literal: 1 } }); expect(selectInitialEvidence(r)).toBe("primary"); });
  it("rejects invented claim evidence IDs", () => { expect(() => normalizeResearchResponse({ ...base, hits: [hit("real")], claims: [{ claim_id: "claim_1", text: "relación", evidence_ids: ["invented"], primary_evidence_id: "invented" }], primary_evidence_ids: ["invented"] })).toThrow(/trazabilidad/); });
  it("rejects a primary ID that is not associated with its claim", () => { expect(() => normalizeResearchResponse({ ...base, hits: [hit("one"), hit("two")], claims: [{ claim_id: "claim_1", text: "relación", evidence_ids: ["one"], primary_evidence_id: "two" }], primary_evidence_ids: ["two"] })).toThrow(/trazabilidad/); });
  it("falls back only to validated relational relevance", () => { const r = normalizeResearchResponse({ ...base, hits: [hit("noise"), hit("context", "same_fragment_both_terms")] }); expect(selectInitialEvidence(r)).toBe("context"); const noiseOnly = normalizeResearchResponse({ ...base, hits: [hit("noise")] }); expect(selectInitialEvidence(noiseOnly)).toBeNull(); });
  it("preserves literal intent and physical PDF traceability", () => { const source = { ...hit("lmi-node", "direct_relation"), work_code: "lmi", work_title: "Likutey Moharán I — edición española", pdf_page: 96, printed_page: 76, document_id: "document", page_anchor_id: "anchor", physical_file_name: "physical.pdf", source_sha256: "abc", section: "LIKUTEY MOHARÁN #2:7", literal_match_kind: "no_niqqud", language_match: "exact", retrieval_tier: 0 }; const r = normalizeResearchResponse({ ...base, intent: "literal_lookup", hits: [source], claims: [{ claim_id: "literal", text: "Se encontró", strength: "strong", evidence_ids: ["lmi-node"], primary_evidence_id: "lmi-node" }], primary_evidence_ids: ["lmi-node"], evidence_counts: { primary: 1, contextual: 0, additional_literal: 0 } }); expect(r.intent).toBe("literal_lookup"); expect(r.hits[0]).toMatchObject({ document_id: "document", page_anchor_id: "anchor", pdf_page: 96, printed_page: 76, section: "LIKUTEY MOHARÁN #2:7" }); });
  it("preserves the validated multilingual interpretation and fallback audit", () => { const interpretation = { language: "he", secondary_languages: [], intent: "concept_lookup", instruction_language: "he", instruction: "איפה נמצא", query_subjects: [{ kind: "concept", raw: "העקרב", normalized: "עקרב", language: "he", script: "hebrew", variants: [{ value: "העקרב", kind: "exact" }, { value: "עקרב", kind: "definite_article_removed" }] }], literal_phrases: [], relations: [], requested_works: [], confidence: 0.95, ai_used: false, fallback_used: true }; const r = normalizeResearchResponse({ ...base, intent: "concept_lookup", interpretation }); expect(r.interpretation).toEqual(interpretation); expect(r.interpretation?.query_subjects[0]).toMatchObject({ raw: "העקרב", normalized: "עקרב" }); expect(r.interpretation?.fallback_used).toBe(true); });
});
