<script lang="ts">
  import { onMount, tick } from "svelte";
  import { getMe, getStoredAccessToken, logout } from "../auth/authClient.ts";
  import EnrichedMarkdownAnswer from "./EnrichedMarkdownAnswer.svelte";
  import SourcePanel from "./SourcePanel.svelte";
  import { askInvestigativeQa, makeRequest, selectInitialEvidence, WORKS, type Hit, type Language, type ResearchResponse } from "./investigativeQaClient.ts";
  import { relevanceLabels, strengthLabel, warningLabel, languageMatchLabel, literalKindLabel, sourceLayerLabels } from "./researchLabels.ts";
  import { composerDirection, isHebrewText, languageAttribute, normalizeDisplayText, safeSnippet, textDirection } from "./textDirection.ts";
  const labels: Record<string, string> = { kitzur: "Kitzur Likutey Moharán", lmi: "Likutey Moharán I — edición española BRI", lmii: "Likutey Moharán II", lh: "Likutey Halajot", lm_xv: "Likutey Moharán XV", potencia_plegaria: "La Potencia de la Plegaria" };
  type Turn = { id: string; question: string; response: ResearchResponse | null; state: "submitting" | "ok" | "partial" | "no_evidence" | "error" };
  let ready = $state(false), inputText = $state(""), isSubmitting = $state(false), requestError = $state<string | null>(null), activeTurnId = $state(""), selectedHitId = $state<string | null>(null);
  let filters = $state({ works: [...WORKS] as string[], languages: ["es", "he", "en"] as Language[], thematic: true, maxHits: 10 });
  let turns = $state<Turn[]>([]), mobilePanel = $state<"sources" | "filters" | "history" | null>(null), restoredPreferences = $state(false);
  let composer: HTMLTextAreaElement, panelTrigger: HTMLElement | null = null;
  const activeTurn = $derived(turns.find((turn) => turn.id === activeTurnId) ?? turns.at(-1));
  const direction = $derived(composerDirection(inputText));
  const hitText = (hit: Hit) => normalizeDisplayText(hit.paragraph_text ?? hit.display_snippet ?? hit.snippet);
  const primaryHits = $derived(activeTurn?.response?.primary_evidence_ids.map((id) => activeTurn.response?.hits.find((hit) => hit.hit_id === id)).filter((hit): hit is Hit => Boolean(hit)) ?? []);
  const additionalHits = $derived(activeTurn?.response?.hits.filter((hit) => ["single_term_literal", "unrelated_literal_noise"].includes(hit.relation_relevance)) ?? []);
  const groupedHits = $derived.by(() => { const groups = new Map<string, Hit[]>(); for (const hit of activeTurn?.response?.hits ?? []) groups.set(hit.work_code, [...(groups.get(hit.work_code) ?? []), hit]); return [...groups.entries()]; });
  onMount(() => { const raw = sessionStorage.getItem("tebaai_research_filters"); if (raw) try { const saved = JSON.parse(raw); filters = { ...filters, ...saved }; } catch { sessionStorage.removeItem("tebaai_research_filters"); } restoredPreferences = true; });
  $effect(() => { if (restoredPreferences) sessionStorage.setItem("tebaai_research_filters", JSON.stringify(filters)); });
  async function submit() { const question = inputText.trim(), token = getStoredAccessToken(); if (!question || !token || isSubmitting) return; const id = crypto.randomUUID(); turns = [...turns, { id, question, response: null, state: "submitting" }]; activeTurnId = id; inputText = ""; isSubmitting = true; requestError = null; try { const response = await askInvestigativeQa(token, makeRequest(question, filters, turns.slice(0, -1).map((turn) => ({ question: turn.question })), null, null)); selectedHitId = selectInitialEvidence(response); turns = turns.map((turn) => turn.id === id ? { ...turn, response, state: response.status } : turn); } catch (error) { inputText = question; requestError = error instanceof Error ? error.message : "No se pudo completar la consulta."; turns = turns.map((turn) => turn.id === id ? { ...turn, state: "error" } : turn); } finally { isSubmitting = false; await tick(); composer?.focus(); } }
  async function verify() { if (!(await getMe())) location.assign("/login"); else { ready = true; await tick(); composer?.focus(); } }
  async function signOut() { await logout(); location.assign("/login"); }
  async function newConversation() { turns = []; activeTurnId = ""; selectedHitId = null; requestError = null; inputText = ""; mobilePanel = null; await tick(); composer?.focus(); }
  function toggleWork(work: string) { const next = filters.works.includes(work) ? filters.works.filter((item) => item !== work) : [...filters.works, work]; if (next.length) filters.works = next; }
  function toggleLanguage(language: Language) { const next = filters.languages.includes(language) ? filters.languages.filter((item) => item !== language) : [...filters.languages, language]; if (next.length) filters.languages = next; }
  async function selectEvidence(evidenceId: string, event?: MouseEvent) { selectedHitId = evidenceId; if (typeof window !== "undefined" && window.innerWidth <= 1100) { panelTrigger = event?.currentTarget as HTMLElement ?? panelTrigger; mobilePanel = "sources"; await tick(); activePanel()?.querySelector<HTMLElement>(`[data-evidence-id="${CSS.escape(evidenceId)}"]`)?.focus(); } }
  async function openPanel(panel: typeof mobilePanel, event: MouseEvent) {
    panelTrigger = event.currentTarget as HTMLElement;
    mobilePanel = panel;
    await tick();
    activePanel()?.querySelector<HTMLElement>('button, input, select, textarea, a[href], [tabindex]:not([tabindex="-1"])')?.focus();
  }
  function closePanel() { mobilePanel = null; tick().then(() => panelTrigger?.focus()); }
  function activePanel() {
    if (mobilePanel === "filters") return document.querySelector<HTMLElement>(".filter-sheet");
    if (mobilePanel === "sources") return document.querySelector<HTMLElement>(".sources.open");
    if (mobilePanel === "history") return document.querySelector<HTMLElement>(".history.open");
    return null;
  }
  function handleKey(event: KeyboardEvent) {
    if (event.key === "Escape" && mobilePanel) { event.preventDefault(); closePanel(); return; }
    if (event.key === "Tab" && mobilePanel) {
      const focusable = [...(activePanel()?.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), a[href], [tabindex]:not([tabindex="-1"])') ?? [])]
        .filter((element) => element.getClientRects().length > 0);
      const first = focusable[0], last = focusable.at(-1);
      if (first && last && (event.shiftKey ? document.activeElement === first : document.activeElement === last)) {
        event.preventDefault();
        (event.shiftKey ? last : first).focus();
      }
    }
    if (event.key === "Enter" && !event.shiftKey && !event.isComposing && event.target === composer) { event.preventDefault(); submit(); }
  }
  function resize(event: Event) { const element = event.currentTarget as HTMLTextAreaElement; element.style.height = "auto"; element.style.height = `${Math.min(element.scrollHeight, 160)}px`; }
  function interpretationView(response: ResearchResponse) {
    const value = response.interpretation;
    if (!value) return null;
    if (["literal_lookup", "translation_or_explanation"].includes(value.intent)) {
      const phrase = value.literal_phrases[0]; return phrase ? { label: "Busqué la frase literal", terms: [phrase.normalized ?? phrase.search_normalized ?? phrase.raw ?? phrase.text ?? ""] } : null;
    }
    if (["relation_query", "comparison_query"].includes(value.intent) && value.relations[0]) return { label: "Comparé los conceptos", terms: [value.relations[0].left.normalized, value.relations[0].right.normalized] };
    if (value.query_subjects.length) return { label: value.intent === "reference_lookup" ? "Busqué la referencia" : "Busqué el concepto", terms: value.query_subjects.map((subject) => subject.normalized) };
    return null;
  }
  const visibleWarnings = (response: ResearchResponse) => response.warnings.filter((warning) => !warning.startsWith("ai_interpretation_fallback:"));
  if (typeof window !== "undefined") verify();
</script>
<svelte:window onkeydown={handleKey} />
{#if ready}
<main class="research" aria-label="Investigación Breslov">
  <header class="research-header"><a href="/" class="research-brand"><span lang="he" dir="rtl">רבי נחמן</span><small>REBE NAJMÁN · BRESLOV RESEARCH</small></a><h1>Investigación</h1><span class="service">● Disponible</span><nav class="mobile-actions" aria-label="Paneles"><button onclick={(e) => openPanel("history", e)}>Conversación</button><button onclick={(e) => openPanel("filters", e)}>Filtros</button><button onclick={(e) => openPanel("sources", e)}>Fuentes</button></nav><button class="desktop-action" onclick={(e) => openPanel("filters", e)}>Filtros</button><button class="desktop-action" onclick={newConversation}>Nueva investigación</button><button class="desktop-action" onclick={signOut}>Cerrar sesión</button></header>
  <aside class:open={mobilePanel === "history"} class="history" aria-label="Conversación de la sesión" role={mobilePanel === "history" ? "dialog" : undefined} aria-modal={mobilePanel === "history" ? "true" : undefined}><div class="aside-head"><h2>Conversación</h2><button class="panel-close" aria-label="Cerrar conversación" onclick={closePanel}>×</button></div><button class="new-research" onclick={newConversation}>＋ Nueva investigación</button>{#if !turns.length}<p>Los turnos de esta sesión aparecerán aquí.</p>{/if}{#each turns as turn, index}<button class:active={turn.id === activeTurnId} onclick={() => { activeTurnId = turn.id; selectedHitId = turn.response ? selectInitialEvidence(turn.response) : null; closePanel(); }}><small>Turno {index + 1}</small>{turn.question}</button>{/each}<a class="aside-link" href="/">Volver al inicio</a><button class="aside-link" onclick={signOut}>Cerrar sesión</button></aside>
  <section class="research-main" aria-live="polite">
    {#if !turns.length}<div class="empty"><p class="kicker">ESPACIO PRIVADO DE ESTUDIO</p><h2>¿Qué querés investigar?</h2><p>Consultá conceptos, fuentes, páginas, referencias y paralelos entre las obras disponibles.</p><div>{#each ["¿Dónde aparece la plegaria?", "¿En qué obras se habla del miedo o temor?", "¿Qué referencias a Rabí Natán aparecen?", "¿Hay notas que mencionen el Zohar?", "¿Cómo se relacionan hitbodedut y plegaria?", "¿Qué se dice sobre la tristeza?"] as example}<button onclick={() => { inputText = example; composer?.focus(); }}>{example}</button>{/each}</div></div>{/if}
    {#if activeTurn}<article class="turn"><div class="user-turn"><p class="speaker">Investigador</p><h2 lang={languageAttribute(activeTurn.question)} dir={textDirection(activeTurn.question)} class:research-hebrew-text={isHebrewText(activeTurn.question)}>{activeTurn.question}</h2></div>{#if activeTurn.state === "submitting"}<p class="loading" role="status">Interpretando la consulta y buscando evidencia en el corpus…</p>{:else if activeTurn.state === "error"}<div class="error" role="alert"><p>{requestError}</p><button onclick={() => submit()}>Reintentar</button></div>{:else if activeTurn.response}{@const view = interpretationView(activeTurn.response)}<p class="speaker">Breslov Research</p>{#if view}<p class="query-interpretation">{view.label}: {#each view.terms.filter(Boolean) as term, index}{#if index}<span aria-hidden="true"> · </span>{/if}<bdi lang={languageAttribute(term)} dir={textDirection(term)}>{term}</bdi>{/each}.</p>{/if}{#if activeTurn.state === "partial"}<p class="partial">La respuesta es parcial: se encontró evidencia en algunas obras o capas, pero no en todas.</p>{:else if activeTurn.state === "no_evidence"}<p class="no-evidence" role="status">No se encontró evidencia suficiente en el corpus consultado.</p>{/if}<section class="synthesis"><h3>Síntesis investigativa</h3><p lang={languageAttribute(activeTurn.response.summary)} dir={textDirection(activeTurn.response.summary)} class:research-hebrew-text={isHebrewText(activeTurn.response.summary)}>{activeTurn.response.summary}</p>{#if activeTurn.response.claims.length}<ol class="claim-list">{#each activeTurn.response.claims as claim}<li><p lang={languageAttribute(claim.text)} dir={textDirection(claim.text)} class:research-hebrew-text={isHebrewText(claim.text)}>{claim.text}</p><span>{strengthLabel(claim.strength)}</span><button aria-label={`Ver fuente de: ${claim.text}`} onclick={(event) => selectEvidence(claim.primary_evidence_id, event)}>Ver fuente</button></li>{/each}</ol>{/if}</section><EnrichedMarkdownAnswer markdown={activeTurn.response.answer_markdown} />
      {#if primaryHits.length}<section class="primary-evidence"><h3>Evidencia principal</h3><div>{#each primaryHits.slice(0,3) as hit}<button class:hebrew-evidence-card={isHebrewText(hitText(hit)) && hitText(hit).length > 260} data-evidence-id={hit.hit_id} onclick={(event) => selectEvidence(hit.hit_id, event)}><strong>{hit.work_title}</strong><span class="evidence-meta" dir="ltr">{hit.physical_pdf_page === null ? "Página no disponible en el registro fuente" : `PDF p. ${hit.physical_pdf_page}${hit.printed_page !== null ? ` · Página impresa ${hit.printed_page}` : ""}${hit.section ? ` · ${hit.section}` : ""}`}</span><small>{sourceLayerLabels[hit.source_layer]} · {literalKindLabel(hit.literal_match_kind) || languageMatchLabel(hit.language_match)}</small><blockquote class:research-hebrew-text={isHebrewText(hitText(hit))} lang={hit.language} dir={hit.direction}>{hitText(hit)}</blockquote></button>{/each}</div></section>{/if}
      <section class="works-results"><h3>Resultados por obra</h3>{#each groupedHits as [work, hits]}<details><summary><strong>{labels[work] ?? work}</strong><span>{hits.length} resultados</span></summary>{#each hits.slice(0,5) as hit}<button onclick={(event) => selectEvidence(hit.hit_id, event)}><span class="evidence-meta" dir="ltr">{hit.pdf_page === null ? "Página no disponible" : `PDF p. ${hit.pdf_page}`} · {relevanceLabels[hit.relation_relevance]}</span><span class:research-hebrew-text={isHebrewText(hitText(hit))} lang={languageAttribute(hitText(hit))} dir={textDirection(hitText(hit))}>{safeSnippet(hitText(hit), 140)}</span></button>{/each}</details>{/each}</section>
      {#if additionalHits.length}<details class="additional-results"><summary>Otras coincidencias literales ({additionalHits.length})</summary><p>Contienen sólo parte de la consulta y no respaldan por sí mismas la relación preguntada.</p></details>{/if}
      <details class="matrix"><summary>Matriz de evidencia</summary><div class="matrix-table" role="table"><div class="matrix-row matrix-head" role="row"><span>Obra</span><span>Principales</span><span>Contextuales</span><span>Adicionales</span><span>Total</span></div>{#each activeTurn.response.evidence_matrix as row}<div class="matrix-row" role="row"><span>{labels[row.work_code] ?? row.work_code}</span><span>{row.primary_hits ?? 0}</span><span>{row.contextual_hits ?? 0}</span><span>{row.additional_literal_hits ?? 0}</span><span>{row.hits}</span></div>{/each}</div></details>
      <details class="matrix"><summary>Cruces entre obras</summary><p>Un paralelo textual no demuestra por sí mismo dependencia, equivalencia o relación doctrinal.</p>{#each activeTurn.response.cross_corpus_matrix as row}<p><strong>{labels[row.work_code] ?? row.work_code}</strong> · {row.relation_type ?? "Co-localización investigativa"} · {row.hits} resultados</p>{/each}</details>
      {#if visibleWarnings(activeTurn.response).length}<section class="research-warnings"><h3>Límites de la respuesta</h3>{#each visibleWarnings(activeTurn.response) as warning}<p>{warningLabel(warning)}</p>{/each}</section>{/if}
      <details class="matrix"><summary>Detalles de la consulta</summary><p>Duración: {activeTurn.response.execution.duration_ms ?? "—"} ms</p><p>{activeTurn.response.execution.used_ai_rendering ? "Redacción automática validada contra evidencia" : "Respuesta determinística segura"}</p>{#if activeTurn.response.interpretation?.fallback_used}<p>La interpretación automática no estuvo disponible; se aplicó el analizador determinístico.</p>{/if}</details>{/if}</article>{/if}
  </section>
  <aside class:open={mobilePanel === "sources"} class="sources" role={mobilePanel === "sources" ? "dialog" : undefined} aria-modal={mobilePanel === "sources" ? "true" : undefined} aria-label="Fuentes del turno"><SourcePanel response={activeTurn?.response ?? null} selectedId={selectedHitId} onselect={(hit) => selectedHitId = hit.hit_id} onclose={closePanel} /></aside>
  <form class="composer" onsubmit={(e) => { e.preventDefault(); submit(); }}><label for="research-question">Nueva pregunta</label><textarea bind:this={composer} id="research-question" data-testid="research-question" bind:value={inputText} dir={direction} lang={languageAttribute(inputText)} class:research-hebrew-text={direction === "rtl"} oninput={resize} maxlength="1000" placeholder="Escribí una pregunta de investigación…" disabled={isSubmitting}></textarea>{#if inputText.length > 850}<small>{inputText.length}/1000</small>{/if}<button data-testid="research-submit" type="submit" disabled={isSubmitting || !inputText.trim()}>Enviar</button></form>
  {#if mobilePanel === "filters"}<div class="panel-backdrop" role="presentation" onclick={closePanel}></div><section class="filter-sheet" role="dialog" aria-modal="true" aria-label="Filtros de investigación"><header><h2>Filtros</h2><button aria-label="Cerrar filtros" onclick={closePanel}>×</button></header><fieldset><legend>Obras</legend>{#each WORKS as work}<label><input type="checkbox" checked={filters.works.includes(work)} onchange={() => toggleWork(work)} /> {labels[work]}</label>{/each}</fieldset><fieldset><legend>Idiomas</legend>{#each [["es","Español"],["he","Hebreo"],["en","Inglés"]] as language}<label><input type="checkbox" checked={filters.languages.includes(language[0] as Language)} onchange={() => toggleLanguage(language[0] as Language)} /> {language[1]}</label>{/each}</fieldset><label><input type="checkbox" checked={filters.thematic} onchange={(e) => filters.thematic = e.currentTarget.checked} /> Incluir paralelos temáticos</label><label>Resultados <select bind:value={filters.maxHits}><option value={5}>5</option><option value={10}>10</option><option value={20}>20</option></select></label><button class="apply-filters" onclick={closePanel}>Aplicar filtros</button></section>{/if}
  {#if mobilePanel && mobilePanel !== "filters"}<button class="panel-backdrop" aria-label="Cerrar panel" onclick={closePanel}></button>{/if}
</main>
{:else}<main class="research research--checking" aria-live="polite"><p>Verificando acceso…</p></main>{/if}
